### ISSUE TITLE
Closed mixin not working as expected

### ISSUE THREAD

**Issue by mukundshah** [justinweinberg/mixwith.ts#1]
> Firstly, I'd like to express my gratitude to the for the efforts put on this project. Your work is very much appreciated and has been a real savior.  

I've encountered an issue with closed mixins not working as expected. The mixin seems to allow extension of classes that don't satisfy the constraint, which should theoretically cause a type error.

### Code Example
```typescript
import { mix, type Constructable } from "mixwith.ts";

class NotBaseController { }

class BaseController {
  get_queryset(): any[] {
    return ["Hello", "World"];
  }
}

const PostMixin = <T extends Constructable<BaseController>>(superclass: T) =>
  class PostMixin extends superclass {
    create(...args: any[]): Response {
      const qs = this.get_queryset();
      console.log(qs);
      return new Response(JSON.stringify(qs));
    }
  };

class Controller extends mix(BaseController).with(PostMixin) { }

const controller = new Controller();
controller.create(1, 2, 3);
// Expected: Response { body: '[]' }

class NotController extends mix(NotBaseController).with(PostMixin) { }
// Expected Error: Type 'NotBaseController' does not satisfy the constraint 'Constructable<BaseController>'.

const notController = new NotController();
notController.create(1, 2, 3);
```
### Expected Behavior

The `NotController` class should not compile, as `NotBaseController` doesn't satisfy the constraint `Constructable<BaseController>`.

### Actual Behavior
The code compiles without errors, allowing the creation and use of `NotController`.

### Environment

- Typescript: `5.5.4`
- mixwith.ts: `1.1.3`
- tsx: `4.15.6`
- node: `20.12.2`

### Additional Notes
This behavior seems to contradict the expected type safety of closed mixins. Any insights or guidance on resolving this issue would be greatly appreciated.

**Comment by justinweinberg** [comment]
Hi there.  I missed this because I didn't have issue tracking on.  I'm tracking now.

As I understand tsx, it doesn't type check your code as stated [here](https://tsx.is/typescript#:~:text=tsx%20does%20not%20type%20check,checking%20step%20in%20your%20projects.)


If you use tsc instead with the --strict option, you should get a error TS2345. 

```
npx tsc --noEmit --strict index.ts
```

results in 

```
index.ts:26:57 - error TS2345: Argument of type '<T extends Constructable<BaseController>>(superclass: T) => { new (...args: any[]): PostMixin; prototype: PostMixin<any>.PostMixin; } & T' is not assignable to parameter of type 'mixin<typeof NotBaseController, { new (...args: any[]): PostMixin<Constructable<BaseController>>.PostMixin; prototype: PostMixin<...>.PostMixin; } & Constructable<...>>'.
  Types of parameters 'superclass' and 'args' are incompatible.
    Type 'typeof NotBaseController' is not assignable to type 'Constructable<BaseController>'.
      Property 'get_queryset' is missing in type 'NotBaseController' but required in type 'BaseController'.
```



Also in VS Code you will get the red squiggles.

Closing the issue but let me know if you still have problems.
